version: '3.8'

services:
  app:
    image: go_dnd
    build: .
    ports:
      - "9090:9090"
    environment:
      - DATABASE_URL=root:manager1@tcp(db:3306)/go_dnd
      - SERVER_ADDRESS=0.0.0.0:9090
    depends_on:
      - db
    

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: manager1
      MYSQL_USERNAME: root
      MYSQL_DATABASE: go_dnd
      MYSQL_PASSWORD: manager1
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql

volumes:
  data: